version: "3.7"

services:
  auth:
    command: start-dev --import-realm
    environment:
      GEOVISIO_BASE_URL: http://localhost:5000
      GEOVISIO_CLIENT_SECRET: what_a_secret
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KEYCLOAK_FRONTEND_URL: http://localhost:5000/api/auth/login
      KC_HTTP_PORT: 8182
    healthcheck:
      test: curl --fail http://host.docker.internal:8182/realms/geovisio
      timeout: 5s
      interval: 5s
      retries: 5
      start_period: 60s
    image: quay.io/keycloak/keycloak:24.0.1
    ports:
      - 8182:8182
    volumes:
      - ./keycloak-realm.json:/opt/keycloak/data/import/geovisio_realm.json
    extra_hosts:
      - "host.docker.internal:192.168.67.2"

  backend:
    image: geovisio/api:2.4.0
    command: api
    volumes:
      - pic_data:/data/geovisio
    ports:
      - 5000:5000
    depends_on:
      - db
    restart: always
    environment:
      - DB_URL=postgres://gvs:gvspwd@db/geovisio
      - OAUTH_OIDC_URL=http://host.docker.internal:8182/realms/geovisio
      - OAUTH_PROVIDER=oidc
      - OAUTH_CLIENT_ID=geovisio
      - OAUTH_CLIENT_SECRET=what_a_secret
      - FLASK_SECRET_KEY=hohwqut73E1gFw6yDlIbM0B3lLK0sAhd
    extra_hosts:
      - "host.docker.internal:192.168.67.2"

  db:
    image: postgis/postgis:13-3.2
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=gvs
      - POSTGRES_PASSWORD=gvspwd
      - POSTGRES_DB=geovisio
    healthcheck:
      # double check to detect the fact that PG starts twice on startup
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER && sleep 1 && pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 5
      start_period: 60s

volumes:
  postgres_data:
  pic_data: {}
