version: "3.7"

services:
  backend:
    image: geovisio/api:2.4.0
    command: api
    volumes:
      - pic_data:/data/geovisio
    ports:
      - 5000:5000
    depends_on:
      - db
    restart: always
    environment:
      - DB_URL=postgres://gvs:gvspwd@db/geovisio
  db:
    image: postgis/postgis:13-3.2
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=gvs
      - POSTGRES_PASSWORD=gvspwd
      - POSTGRES_DB=geovisio
    healthcheck:
      # double check to detect the fact that PG starts twice on startup
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER && sleep 1 && pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 5
      start_period: 60s

volumes:
  postgres_data:
  pic_data: {}
