name: Build app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
          channel: 'stable'
    - name: Build apk
      run: flutter build apk --debug
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
         name: app_debug
         path: build/app/outputs/flutter-apk/app-debug.apk
