name: Build app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '1.8'
        distribution: 'temurin'
    - uses: subosito/flutter-action@v1
       with:
          flutter-version: '2.5.0'
